FROM ubuntu
MAINTAINER logiclabs

RUN apt-get update
RUN apt-get install -y default-jdk

COPY . /usr/src/myapp/
WORKDIR /usr/src/myapp/
RUN apk --no-cache add maven && mvn --version
RUN mvn package


FROM openjdk:8-jre-alpine3.7
WORKDIR /root/


ARG JAR_FILE= /usr/src/myapp/target/dockerbasico-0.0.1-SNAPSHOT.jar
ADD ${JAR_FILE} app.jar

EXPOSE 9091
ENTRYPOINT ["java", "-jar", "./app.jar"]
