FROM openjdk:8-jdk-alpine3.7 AS builder
RUN java -version

COPY . /usr/src/myapp/
WORKDIR /usr/src/myapp/
RUN apk --no-cache add maven && mvn --version
RUN mvn package


FROM openjdk:8-jre-alpine3.7
WORKDIR /root/
COPY --from=builder /usr/src/myapp/target/SpringBootExample-0.0.1-SNAPSHOT.jar .

EXPOSE 9091
ENTRYPOINT ["java", "-jar", "./SpringBootExample-0.0.1-SNAPSHOT.jar"]
